name: Bun Build Flow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash

    - name: Build project
      run: |
        bun install
        bun run build
